CREATE DATABASE TCC
USE TCC

CREATE TABLE CONDOMINIO
(
	COND_INT_ID INT IDENTITY(1,1) CONSTRAINT PK_CONDOMINIO_ID PRIMARY KEY,
	COND_STR_NOME VARCHAR(25) NOT NULL,
	COND_STR_END VARCHAR(50) NOT NULL,
	COND_INT_APTOS INT NOT NULL,
	COND_STR_CARAC VARCHAR(1) NOT NULL
)

CREATE TABLE MORADOR
(
	MOR_INT_ID INT IDENTITY(1,1) CONSTRAINT PK_MORADOR_ID PRIMARY KEY,
	MOR_STR_NOME VARCHAR(50) NOT NULL,
	MOR_STR_LGN VARCHAR(50) NOT NULL,
	MOR_STR_PSW VARCHAR(100) NOT NULL,
	MOR_STR_IMG VARCHAR(500),
	MOR_STR_CEL VARCHAR(11),
	MOR_DT_ING DATE NOT NULL,
	MOR_BIT_ATIVO BIT NOT NULL,
	MOR_BIT_REP BIT NOT NULL,
	MOR_BIT_SIN BIT NOT NULL,
	MOR_STR_PSWRTOKEN VARCHAR(100),
	MOR_DT_PSWREXP DATE,
	MOR_INT_PSWPORTA INT NOT NULL,
	COND_INT_ID INT NOT NULL CONSTRAINT FK_MORADOR_CONDOMINIO REFERENCES CONDOMINIO
)

CREATE TABLE LOGGER
(
	LOG_INT_ID INT IDENTITY(1,1) CONSTRAINT PK_LOGGER_ID PRIMARY KEY,
	LOG_STR_MSG VARCHAR(320) NOT NULL,
	LOG_DT_EMI DATETIME NOT NULL,
	COND_INT_ID INT NOT NULL CONSTRAINT FK_LOGGER_CONDOMINIO REFERENCES CONDOMINIO,
)

CREATE TABLE BLOCO
(
	BLO_INT_ID INT IDENTITY(1,1) CONSTRAINT PK_BLOCO_ID PRIMARY KEY,
	BLO_STR_NOME VARCHAR(25),
	COND_INT_ID INT NOT NULL CONSTRAINT FK_BLOCO_CONDOMINIO REFERENCES CONDOMINIO
)

CREATE TABLE APARTAMENTO
(
	APTO_INT_ID INT IDENTITY(1,1) CONSTRAINT PK_APARTAMENTO_ID PRIMARY KEY,
	APTO_INT_NUM INT NOT NULL,
	APTO_INT_AND INT,
	MOR_INT_ID INT CONSTRAINT FK_APARTAMENTO_MORADOR REFERENCES MORADOR,
	BLO_INT_ID INT NOT NULL CONSTRAINT FK_APARTAMENTO_BLOCO REFERENCES BLOCO,
	COND_INT_ID INT NOT NULL CONSTRAINT FK_APARTAMENTO_CONDOMINIO REFERENCES CONDOMINIO
)

CREATE TABLE LOCAIS
(
	LOC_INT_ID INT IDENTITY(1,1) CONSTRAINT PK_LOCAIS_ID PRIMARY KEY,
	LOC_STR_NOME VARCHAR(25) NOT NULL,
	LOC_INT_QTDE INT NOT NULL,
	LOC_STR_DESC VARCHAR(320) NOT NULL,
	COND_INT_ID INT NOT NULL CONSTRAINT FK_LOCAIS_CONDOMINIO REFERENCES CONDOMINIO
)

CREATE TABLE DESPESAS
(
	DESP_INT_ID INT IDENTITY(1,1) CONSTRAINT PK_DESPESAS_ID PRIMARY KEY,
	DESP_STR_DESC VARCHAR(200) NOT NULL,
	DESP_NM_VAL NUMERIC(10,2) NOT NULL,
	DESP_DT_DATA DATETIME NOT NULL,
	COND_INT_ID INT NOT NULL CONSTRAINT FK_DESPESAS_CONDOMINIO REFERENCES CONDOMINIO
)

CREATE TABLE FUNCIONARIO
(
	FUNC_INT_ID INT IDENTITY(1,1) CONSTRAINT PK_FUNCIONARIO_ID PRIMARY KEY,
	FUNC_STR_NOME VARCHAR(50) NOT NULL,
	FUNC_DT_ADMIS DATETIME NOT NULL,
	FUNC_STR_CEL VARCHAR(11) NOT NULL,
	FUNC_STR_CARGO VARCHAR(50) NOT NULL,
	FUNC_STR_EMPR VARCHAR(50),
	COND_INT_ID INT NOT NULL CONSTRAINT FK_FUNCIONAIRO_CONDOMINIO REFERENCES CONDOMINIO
)

CREATE TABLE VISITAS
(
	VSIT_INT_ID INT IDENTITY(1,1) CONSTRAINT PK_VISITAS_ID PRIMARY KEY,
	VSIT_STR_NOME VARCHAR(25) NOT NULL,
	VSIT_DT_ENT DATETIME NOT NULL,
	MOR_INT_ID INT NOT NULL CONSTRAINT FK_VISITAS_MORADOR REFERENCES MORADOR,
	COND_INT_ID INT NOT NULL CONSTRAINT FK_VISITAS_CONDOMINIO REFERENCES CONDOMINIO
)

CREATE TABLE RESERVAS
(
	RES_INT_ID INT IDENTITY(1,1) CONSTRAINT PK_RESERVAS_ID PRIMARY KEY,
	RES_DT_CMC DATETIME NOT NULL,
	RES_DT_TER DATETIME NOT NULL,
	RES_INT_QTDE INT NOT NULL,
	MOR_INT_ID INT NOT NULL CONSTRAINT FK_RESERVAS_MORADOR REFERENCES MORADOR,
	LOC_INT_ID INT NOT NULL CONSTRAINT FK_RESERVAS_LOCAIS REFERENCES LOCAIS,
	COND_INT_ID INT NOT NULL CONSTRAINT FK_RESERVAS_CONDOMINIO REFERENCES CONDOMINIO
)

CREATE TABLE COMUNICADOS
(
	COMU_INT_ID INT IDENTITY(1,1) CONSTRAINT PK_COMU_ID PRIMARY KEY,
	COMU_STR_TIT VARCHAR(50) NOT NULL,
	COMU_STR_DESC VARCHAR(600) NOT NULL,
	COMU_DT_DATA DATETIME NOT NULL,
	MOR_INT_ID INT NOT NULL CONSTRAINT FK_COMUNICADOS_MORADOR REFERENCES MORADOR,
	COND_INT_ID INT NOT NULL CONSTRAINT FK_COMUNICADOS_CONDOMINIO REFERENCES CONDOMINIO
)

CREATE TABLE ASSISTENCIA
(
	AST_INT_ID INT IDENTITY(1,1) CONSTRAINT PK_ASSISTENCIA_ID PRIMARY KEY,
	AST_DT_DATA DATETIME NOT NULL,
	AST_STR_TIT VARCHAR(50) NOT NULL,
	AST_STR_DESC VARCHAR(320) NOT NULL,
	AST_STR_TIPO VARCHAR(25) NOT NULL,
	MOR_INT_ID INT NOT NULL CONSTRAINT FK_ASSISTENCIA_MORADOR REFERENCES MORADOR,
	COND_INT_ID INT NOT NULL CONSTRAINT FK_ASSISTENCIA_CONDOMINIO REFERENCES CONDOMINIO
)

CREATE TABLE IMPOSTO
(
	IMP_INT_ID INT IDENTITY(1,1) CONSTRAINT PK_IMPOSTO_ID PRIMARY KEY,
	IMP_DT_DATA DATE NOT NULL,
	IMP_NM_VAL NUMERIC(10,2) NOT NULL,
	IMP_STR_DESC VARCHAR(320) NOT NULL,
	APTO_INT_ID INT NOT NULL CONSTRAINT FK_IMPOSTO_APARTAMENTO REFERENCES APARTAMENTO,
	COND_INT_ID INT NOT NULL CONSTRAINT FK_IMPOSTO_CONDOMINIO REFERENCES CONDOMINIO
)

CREATE TABLE VAGAS
(
	VAG_INT_ID INT IDENTITY(1,1) CONSTRAINT PK_VAGAS_ID PRIMARY KEY,
	APTO_INT_ID INT NOT NULL CONSTRAINT FK_VAGAS_APARTAMENTO REFERENCES APARTAMENTO,
	BLO_INT_ID INT NOT NULL CONSTRAINT FK_VAGAS_BLOCO REFERENCES BLOCO,
	VAG_STR_NUM VARCHAR(15) NOT NULL,
)

CREATE TABLE MENSAGENS
(
	MSG_INT_ID INT IDENTITY(1,1) CONSTRAINT PK_MENSAGEM_ID PRIMARY KEY,
	MOR_INT_ID INT NOT NULL CONSTRAINT FK_MENSAGENS_MORADOR REFERENCES MORADOR,
	MSG_STR_DESC VARCHAR(320) NOT NULL,
	MSG_DT_DATA DATETIME NOT NULL,
	MSG_INT_DEST INT NOT NULL
)

CREATE TABLE CONTATO
(
	CONT_INT_ID INT IDENTITY(1,1) CONSTRAINT PK_CONTATO_ID PRIMARY KEY,
	CONT_STR_NOME VARCHAR(25) NOT NULL,
	CONT_STR_EMAIL VARCHAR(50) NOT NULL,
	CONT_STR_END VARCHAR(50),
	CONT_STR_DESC VARCHAR(500) NOT NULL,
	CONT_INT_APTOS INT
)

CREATE TABLE POST
(
	POST_INT_ID INT IDENTITY(1,1) CONSTRAINT PK_POST_ID PRIMARY KEY,
	MOR_INT_ID INT NOT NULL CONSTRAINT FK_POST_MORADOR REFERENCES MORADOR,
	COND_INT_ID INT NOT NULL CONSTRAINT FK_POST_CONDOMINIO REFERENCES CONDOMINIO,
	POST_DT_DATA DATETIME NOT NULL,
	POST_STR_DESC VARCHAR(500) NOT NULL
)

CREATE TABLE SEGUIDORES
(
	SEG_INT_ID INT IDENTITY(1,1) CONSTRAINT PK_SEGUIDORES_ID PRIMARY KEY,
	MOR_INT_ID INT NOT NULL CONSTRAINT FK_SEGUIDORES_MORADOR REFERENCES MORADOR,
	SEG_INT_MOR INT NOT NULL,
)

CREATE TABLE VOTACAO
(
	VOT_INT_ID INT IDENTITY(1,1) CONSTRAINT PK_VOTACAO_ID PRIMARY KEY,
	MOR_INT_ID INT NOT NULL CONSTRAINT FK_VOTACAO_MORADOR REFERENCES MORADOR,
	COND_INT_ID INT NOT NULL CONSTRAINT FK_VOTACAO_CONDOMINIO REFERENCES CONDOMINIO,
	VOT_STR_TITULO VARCHAR(25) NOT NULL,
	VOT_STR_DESC VARCHAR(150) NOT NULL,
	VOT_DT_DATA DATETIME NOT NULL,
)

CREATE TABLE REGRAS
(
	REG_INT_ID INT IDENTITY(1,1) CONSTRAINT PK_REGRAS_ID PRIMARY KEY,
	COND_INT_ID INT NOT NULL CONSTRAINT FK_REGRAS_CONDOMINIO REFERENCES CONDOMINIO,
	REG_STR_DESC VARCHAR(100) NOT NULL
)

CREATE TABLE VOTO
(
	VOTO_INT_ID INT IDENTITY(1,1) CONSTRAINT PK_VOTO_ID PRIMARY KEY,
	COND_INT_ID INT NOT NULL CONSTRAINT FK_VOTO_CONDOMINIO REFERENCES CONDOMINIO,
	MOR_INT_ID INT NOT NULL CONSTRAINT FK_VOTO_MORADOR REFERENCES MORADOR,
	VOT_INT_ID INT NOT NULL CONSTRAINT FK_VOTO_VOTACAO REFERENCES VOTACAO,
	VOTO_BIT_OPCAO BIT NOT NULL
)

SELECT *
FROM CONDOMINIO
SELECT *
FROM MORADOR
SELECT *
FROM LOGGER
SELECT *
FROM BLOCO
SELECT *
FROM APARTAMENTO
SELECT *
FROM LOCAIS
SELECT *
FROM DESPESAS
SELECT *
FROM FUNCIONARIO
SELECT *
FROM VISITAS
SELECT *
FROM RESERVAS
SELECT *
FROM COMUNICADOS
SELECT *
FROM ASSISTENCIA
SELECT *
FROM IMPOSTO
SELECT *
FROM VAGAS
SELECT *
FROM MENSAGENS
SELECT *
FROM CONTATO
SELECT *
FROM POST
SELECT *
FROM SEGUIDORES
SELECT *
FROM VOTACAO
SELECT *
FROM REGRAS
SELECT *
FROM VOTO

SELECT DATEADD(DAY, 7, CURRENT_TIMESTAMP)
SELECT DATEADD(DAY, 7, GETDATE())

DROP TABLE CONDOMINIO
DROP TABLE MORADOR
DROP TABLE LOGGER
DROP TABLE BLOCO
DROP TABLE APARTAMENTO
DROP TABLE LOCAIS
DROP TABLE DESPESAS
DROP TABLE FUNCIONARIO
DROP TABLE VISITAS
DROP TABLE RESERVAS
DROP TABLE COMUNICADOS
DROP TABLE ASSISTENCIA
DROP TABLE IMPOSTO
DROP TABLE VAGAS
DROP TABLE MENSAGENS
DROP TABLE CONTATO
DROP TABLE POST
DROP TABLE SEGUIDORES
DROP TABLE VOTACAO
DROP TABLE REGRAS
DROP TABLE VOTO

USE master
DROP DATABASE TCC

UPDATE MORADOR SET MOR_BIT_SIN = 1 WHERE MOR_INT_ID = 2

